# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Penesive
tagline:             'Random Experiments'
description:          This blog will be my notepad of things i learn , new programming language, tools , compilers and even skate boarding.I would look at this blog as more of my penesive to see how much my understanding of things have changed.
url:                 http://pradheepshrinivasan.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Pradheep Shrinivasan
  url:               http://pradheepshrinivasan.github.io/
  email:             pradheep.sh@gmail.com

# Custom vars
version:             1.0.0
